README.md, requirements-dev.txt
Add filters to `requirements-dev.txt` to prevent requires.io from making integer (non-backwards-compatible) suggestions.
https://requires.io/features/
=> Add requires.io filters

setup.py
This adds various new capabilities. The most important of these is adding a `path` attribute to items in error logs, providing an XPath to indicate where a problem occurred in the source document.
=> Update lxml to 3.8.0

Makefile, requirements-dev.txt
A couple of reqquirements are being updated to the next integer. The primary reason for integer in both cases is dropping of Python 2.6 support. As such, this update doesn't really impact iati.core
=> Undertake integer requirements updates

iati/core/utilities.py
The statement `from io import StringIO` is valid
in both python2 and python3.
=> Remove try/except block in StringIO import

setup.cfg
The unnecessary '-' character was removed.
=> Fix pytest config

README.md, iati/core/__init__.py, iati/core/codelists.py, iati/core/default.py, iati/core/schemas.py, iati/core/tests/test_codelists.py, iati/core/tests/test_data.py, iati/core/tests/test_default.py, iati/core/tests/test_schemas.py, iati/core/tests/test_utilities.py, iati/core/utilities.py, iati/tests/test_validate.py, iati/validate.py
Simplifies the way functions are called. This effectively
renames library functions as follows:
`iati.core.codelists.Code` -> `iati.core.Code`
`iati.core.codelists.Codelist` -> `iati.core.Codelist`
`iati.core.data.Dataset` -> `iati.core.Dataset`
`iati.core.rulesets.Rule` -> `iati.core.Rule`
`iati.core.rulesets.Ruleset` -> `iati.core.Ruleset`
`iati.core.schema.Schema` -> `iati.core.Schema`
=> [#31] Reduce the verbosity of function calls

LICENSES-3RD-PARTY.txt, iati/core/resources.py, iati/core/tests/test_resources.py, requirements-dev.txt
Ensures iati.core.resources.load_as_string now returns a string,
whilst adding iati.core.resources.load_as_bytes to return a bytes
object. Adds tests for both functions.
=> [#42] Refector to align function names with outputs

iati/core/resources.py, iati/core/tests/utilities.py
It was noted that it was challenging to understand each how `resources.py` works, and how to load in test data.
This improves documentation and fixes method ordering so that clarity is improved.
=> Improve test resources clarity

iati/core/default.py, iati/core/rulesets.py, iati/core/tests/test_default.py
To do this, all the various types of Rule subclass need creating.
These subclasses have been created, but need tests writing for them.
=> Make iati.core.default.ruleset() return a Ruleset, not string

iati/core/rulesets.py, iati/core/tests/test_rulesets.py
This allows the properties to be accessed directly rather than through a case.
=> Extract Rule case properties

iati/core/rulesets.py, iati/core/tests/test_rulesets.py
This is done by combining it with paths at the point of initialisation.
=> Remove need to refer to `xpath_base` when using a Rule

iati/core/rulesets.py, iati/core/tests/test_rulesets.py
Because no_more_than_one appeared early, it was not in alphabetical order with the other Rules. This brings it to the correct place in the alphabet.
=> Alphabetise no_more_than_one

iati/core/schemas.py, iati/core/tests/test_schemas.py
This makes _flatten_includes a private method, and adds to the `__init__` method
of `iati.core.Schema`. Also simplifies existing tests, and adds a test for
a schema that does not feature an include statement.
=> Flatten schema in init

.gitignore, iati/core/codelists.py, iati/core/resources/test_data/202/valid_iati_incomplete_codelist_code_not_present.xml, iati/core/resources/test_data/202/valid_iati_incomplete_codelist_code_present.xml, iati/core/tests/test_codelists.py, iati/core/tests/utilities.py, iati/tests/test_validate.py, iati/validate.py
In an incomplete Codelist, it is deemed that not all values are present. As such, using a value not on the Codelist leads to valid data.
=> Deal with incomplete Codelists

iati/tests/test_validate.py
There was a duplicate function name due to a copypaste error. The two functions now have different names.
=> Rename a duplicate function name

iati/validate.py
The warning was about a change that has already occured
=> Remove now out-of-date warning

.gitignore, Makefile, iati/core/tests/utilities.py, requirements-dev.txt
This makes the tests parallisable.
The primary change is that dictionary keys in `find_parameter_by_type` are sorted so that the order of the returned array is the same every time.
Note that running tests in parallel is currently slower than running them sequentially.
=> Parallel tests

iati/tests/test_validator.py, iati/validator.py
Implement Validation errors using classes.
This will be based loosely on the [cerberus](http://docs.python-cerberus.org/en/stable/errors.html) implementation, providing a public API along the lines of `ValidationError in ErrorList`.
Alternatives that have been looked at but rejected at this point:
* [voluptuous](https://pypi.python.org/pypi/voluptuous) - `raise Invalid()` - we need to keep track of errors, not raise them
* [JSONSchema](http://python-jsonschema.readthedocs.io/en/latest/errors/) - `ValidationError(_Error)` on `Validator` - there is currently not a distinct `Validator` object, and putting such a thing on, eg, a `Dataset` doesn't seem appropriate
* [lxml](https://github.com/lxml/lxml/blob/621d8d9f0c2dda3f97ffa6eec568fc7eea98ebb1/src/lxml/xmlerror.pxi) - `_LogEntry in …
=> Class-based Validation Error Log

iati/tests/test_validator.py, iati/validator.py
This specifically looks at iterables and non-iterables as the two key types of value to pass in.
Iterables should silently fail to add anything, while non-iterables should raise a TypeError.
=> Test extending a ValidationErrorLog with invalid values

iati/core/data.py, iati/core/exceptions.py, iati/core/tests/test_data.py, iati/tests/test_validator.py, iati/validator.py
By using validator to determine whether something is XML, the code is more DRY. It also allows more detailed errors to be provided.
This change makes `iati.validator` a dependency of `iati.core`.
=> Switch Dataset creation to use iati.validator

README.md, iati/core/__init__.py, iati/core/default.py, iati/core/resources.py, iati/core/schemas.py, iati/core/tests/test_data.py, iati/core/tests/test_default.py, iati/core/tests/test_resources.py, iati/core/tests/test_schemas.py, iati/core/tests/test_utilities.py, iati/core/tests/utilities.py, iati/core/utilities.py, iati/tests/test_validate.py, iati/validate.py
- Creates `ActivitySchema` and `OrganisationSchema` classes (both children of `iati.core.schema.Schema`)
- Changes how `iati.core.schema.Schema` (and subclasses) are instantiated (now using a filepath, rather than a schema name)
- Adds new functions `get_all_activity_schema_paths` and `get_all_organisation_schema_paths`
- Creates `iati.core.default.schema(schema_name)` as a means of instantiating a default IATI schema (and updates README with usage information)
- Renames functions for clarity: `find_all_*schema_paths` -> `get_all_*schema_paths`
=> Improvements to iati.core.schema.Schema

iati/core/data.py, iati/core/exceptions.py, iati/core/tests/test_data.py, iati/tests/test_validator.py, iati/validator.py
When `is_xml()` indicates that a value is not XML, errors are produced.
This PR adds such errors to a `ValidationErrorLog`.
=> Add `is_xml()` errors to error log

iati/core/resources.py
The check for whether a file had the Codelist extension was being performed after trying to load the file. This was causing non-Codelist files to be looked for.
The check is now being performed before attempting to load the files so that it's less likely that a file will not be found. Note that there may still be errors raised should a file be deleted in the time between the check and the loading.
Fixes #18
=> Filter file names before access - fixes #18

iati/core/tests/test_data.py, iati/core/tests/test_default.py, iati/core/tests/test_utilities.py, iati/core/tests/utilities.py
The new name is clearer in what it does. A parameter has also been inverted to make slightly more sense.
Based on #63
Three find+replace regex pairs for conversion:
* `iati\.core\.tests\.utilities\.find_parameter_by_type\((\[(.*,?\s?)?\]),\s?False\)` -> `iati\.core\.tests\.utilities\.generate_test_types\($1, True\)`
* `iati\.core\.tests\.utilities\.find_parameter_by_type\((\[(.*,?\s?)?\]),\s?True\)` -> `iati\.core\.tests\.utilities\.generate_test_types\($1, False\)`
* `iati\.core\.tests\.utilities\.find_parameter_by_type\((\[(.*,?\s?)?\])\)` -> `iati\.core\.tests\.utilities\.generate_test_types\($1\)`
=> Rename test function generate_test_types() - fixes #63

iati/core/tests/test_data.py, iati/core/tests/utilities.py, iati/tests/test_validate.py
The addition of a helper function makes the file a fair bit clearer due to a reduction in repeated calls to functions with long names.
=> Make tests/utilities.py easier to read

iati/core/tests/utilities.py
This is generally useful for loading in test files. in a cleaner manner than having double-nested function calls with long prefixes.
=> Add a load_as_dataset function to test utils

iati/core/rulesets.py
Python2.7 does not have a fullmatch function for regexes. This is resolved by setting start and end anchors in the regex of interest.
Having fixed the regex problem, it becomes apparent that there is another problem in that None is orderable at v2 but not v3. This is also fixed.
=> Make date_order rule work in 2.7

iati/core/resources/test_data/202/invalid_nomorethanone.xml, iati/core/resources/test_data/202/valid_nomorethanone.xml, iati/core/rulesets.py, iati/core/tests/test_rulesets.py
The `no more than one` rule only permits a single element or attribute from anywhere in the list of paths. Having one of each of the paths is not a harsh enough restriction.
`There must be no more than one element described by the given paths.`
=> Deal with ambiguous NoMoreThanOne case

iati/core/rulesets.py, iati/core/tests/test_rulesets.py
When a context does not exist, Rules should be `True`.
This was not the case with `AtLeastOne` due to it having inverted logic in comparison to other Rules.
=> Test no context rules

iati/tests/test_validator.py
There is now a load_as_dataset() function. As such, it makes sense to use this where it is necessary to load a Dataset but having access to the original string is not required.
=> Refactor test_validator.py to use test util functions

iati/core/tests/utilities.py
A single call to a local function is much nicer than a nested call to a pair of functions in a different module
=> Utilise a utility function to simplify constant definitions

iati/core/resources.py, iati/core/tests/test_data.py, iati/core/tests/test_resources.py
In several cases, the same function call was being called multiple times when it didn't need to be. This is due to the values previously being a constant, then find+replace happening.
Something similar will likely need doing in other files, though this appears to be all that's in `dev` at present.
=> Fix some find+replace sillyness in `test_data.py`

iati/core/tests/test_default.py, iati/validator.py
This changes dictionary access to use a more sensible iterator
=> 'for _, thing in items()' -> 'for thing in values()'

iati/core/default.py, iati/core/tests/test_default.py, iati/core/tests/test_schemas.py, iati/core/tests/utilities.py
The `iati.core.default` module has functions that return a number of useful default objects. If implemented badly, modification of these values from a calling function will modify the defaults themselves. This would be bad.
This PR adds tests to ensure it is challenging or impossible to accidentally modify defaults. It also improves the implementation by making the interfaces more consistent and less dangerous.
Fixes #148 
Fixes #146
=> Provide safer and cleaner `iati.core.default` interface

iati/core/tests/test_default.py
There are [tests that are failing](https://travis-ci.org/IATI/iati.core/jobs/275133960) on Travis against Python `3.5.3`. They are working locally against Python `3.5.2`. This is odd.
This PR fixes the tests so that they pass.
Should make failing tests in #151 pass
=> Fix flaky `test_default.py` tests

LICENSES-3RD-PARTY.txt
Several 3rd party tools were being used, though were not listed in the relevant document. This adds them.
`pytest-xdist` has no copyright info listed, so there is nothing listed here.
=> Add missing license info

requirements-dev.txt
'six' was specified in both `requirements_dev.txt` and `setup.py`.
This removes it from the .txt file since it's already defined somewhere that is imported when that is run.
=> Remove duplicate dependency

iati/core/resources/test_data/202/invalid_dateorder.xml, iati/core/resources/test_data/202/valid_dateorder.xml, iati/core/rulesets.py, iati/core/tests/test_rulesets.py
This is in response to the change in the issue:
IATI/IATI-Rulesets#41
The PRs relating to changing the Rule itself (in the Rulesets repo) should be merged before this.
=> Change RuleDateOrder to permit equal `less` and `more` values

iati/core/codelists.py
This is required since there are no implicit relationships when comparing objects.
https://docs.python.org/2/reference/datamodel.html#object.__ne__
This was identified by https://lgtm.com/projects/g/IATI/iati.core/alerts/?mode=list
https://stackoverflow.com/questions/4352244/python-should-i-implement-ne-operator-based-on-eq has more info
=> Check code and codelist inequality

.travis.yml, Makefile
master should only have well-linting code in it. Note that this is probably a tad strict at present due to some linter errors we don't care about not being ignored.
This uses Travis features released today https://github.com/travis-ci/beta-features/issues/28 - other conditions and build stages could be added if desired (it's a pretty cool feature, though the syntax isn't entirely obvious).
=> Add strict linting when merging to master

README.md
Remove a reference to `iati.core.resources` where the data being loaded is not distributed as part of the library.
=> Update README.md - remove incorrect `resources` reference

README.md, setup.py
This is in-line with other ways that the library is being referenced.
=> Change name in top-level places from iati.core to pyIATI

iati/tests/test_data.py
Since lxml v4.0.0, a bug has been resolved, where previously
`etree.fromstring()` failed to parse UTF-32 data with BOM.
=> Add tests for raw datasets encoded in UTF-32

.travis.yml
The tests (eg. https://travis-ci.org/IATI/pyIATI/jobs/289934687) to merge into `master` are failing because of a missing dependency in a specific test that only runs when merging into master.
=> Add missing lxml to travis install

CHANGELOG.md, MANIFEST.in, setup.py
The source distribution package requires that a MANIFEST.in file
is added to the respoitory, to ensure that the resources folder
is shipped with the code.
This change is tested locally using `python setup.py sdist`, which results in a `dist/pyIATI-0.1.0.tar.gz` file, which – when uncompressed – contains the folder `iati/resources`.
=> Add resources folder to package distribution

setup.py
It was decided to not remove the tests folder from sdist packaging.
This will enable unpackaging for tests to be run before uploading a
planned release to pypi.
=> Fix exclude pattern in setup.py

.travis.yml
`dev` should always be in a state that could be merged to `master` after a version bump.
Without strict linting, this is not possible. As such, this adds strict linting when merging to `dev`.
=> Add strict lintin` when merging to dev

CHANGELOG.md, iati/resources/test_data/202/valid_iati_use_xml_lang.xml, iati/tests/test_validator.py, iati/validator.py
This is a fix to the bug identified by @andylolz in https://github.com/IATI/pyIATI/pull/45#issuecomment-342554472 - Codelist validation would raise a key error for any dataset with an `xml:lang` attribute.
This is a specific fix to the `xml:lang` problem. It does not address the issues that the current code does not support custom namespaces (though this is a larger problem).
=> Convert 'xml:lang' attribute to use namespace when performing Codelist checks

CHANGELOG.md, iati/default.py, iati/tests/test_default.py
Some, but not all, functions in iati.default had it documented and tested that the error could be raised.
This makes the documentation and testing more comprehensive.
=> Test for and document undocumented potential ValueErrors

CHANGELOG.md, iati/codelists.py, iati/tests/test_codelists.py
Codelists contain Codes within a set. This means that they are in no particular order. Hash functions require input in the same order to produce the same output.
This sorts the Codes in a Codelist before hashing so that Codelists with the same Codes hash the same no matter which order the set provides them in.
=> Fix Codelist hashing

CHANGELOG.md, iati/rulesets.py, iati/tests/test_rulesets.py
The `name` of a Rule should not be writable after instantiation.
This changes it from an attribute to a property so that this is the case.
=> Change Rule's `name` attribute to property

CHANGELOG.md, iati/rulesets.py, iati/tests/test_rulesets.py
Rules within a Ruleset should be unique. Being able to change the context impacts how this is done.
At the moment, common properties are being changed. Ones that change based on the specific Rule will be looked at separately.
=> Make a Rule's context read-only after init

CHANGELOG.md, iati/rulesets.py, iati/tests/test_rulesets.py
The values from within the case are extracted into their own properties. These can be accessed instead should the components be needed.
It should not be necessary to externally access the entire case of a Rule as an attribute. If good reason can be provided for why it does need accessing, it can be made public again.
=> Privatise Rule.case

CHANGELOG.md, iati/tests/test_schemas.py
Multiple Rulesets can be added to a Schema now.
As such, the tests can be implemented rather than skipped.
A `not` has been removed due to the complications of handling mutable hashable objects - this is a thing that should be separately looked at properly.
=> Test that multiple Rulesets can be added to a Schema

CHANGELOG.md, iati/tests/resources.py
* A TODO relates to the function being moved to the location it is now in.
* The removed function is not called anywhere.
=> Remove out-of-date code and docs from `iati.tests.resources`

CHANGELOG.md, iati/default.py, iati/resources.py, iati/schemas.py, iati/tests/conftest.py, iati/tests/resources.py, iati/tests/test_codelists.py, iati/tests/test_resources.py, iati/tests/test_schemas.py, iati/tests/test_utilities.py, iati/tests/utilities.py, iati/validator.py
This renames functions as per the proposed changes in #258.
Fixes renaming part of #258
=> Rename functions in `resources.py`

iati/rulesets.py
The fixed error: `R:573, 4: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)`
=> Fix linting fail for check added with pylint 1.8

README.md
Changes the URL for the Travis link so that it is correct.
=> Fix Travis badge link

CHANGELOG.md, iati/constants.py, iati/tests/test_constants.py
This adds a constant to allow explicit specification of Minor versions.
This is partially preemptive of SemVer.
It also adds naming consistency with the equivalent constant for Major versions.
The relevant test has been improved.
=> Add a Minor versions constant

.travis.yml
There is now a 30% speed increase when running tests in parallel locally.
Travis runs on 2-core containers, so this may provide a notable speedup.
https://travis-ci.org/IATI/pyIATI/builds/343745666 vs. (https://travis-ci.org/IATI/pyIATI/builds/343350773 and https://travis-ci.org/IATI/pyIATI/builds/342424174) shows that there is also a notable speedup on Travis.
=> Run travis tests in parallel

CHANGELOG.md, iati/data.py, iati/tests/test_data.py, iati/tests/test_utilities.py, iati/tests/test_validator.py, iati/tests/utilities.py, iati/utilities.py, iati/validator.py
Change required to allow #284 to progress.
Undertaken separately since it does not rely on the changes between 'dev' and #284.
=> Separate testing of `bytes` and `str` type values for Python 3+

CHANGELOG.md, iati/data.py, iati/tests/fixtures/versions.py, iati/tests/test_data.py, iati/tests/test_utilities.py, iati/tests/test_validator.py, iati/tests/test_version.py, iati/tests/utilities.py, iati/utilities.py, iati/validator.py, iati/version.py
Invalid Decimal values were not previously tested when checking for permitted version numbers.
This modifies the test so that they are, and tweaks the code so that the updated test passes.
=> More thoroughly test a version filtering decorator

CHANGELOG.md, iati/resources.py, iati/tests/fixtures/versions.py, iati/tests/resources.py, iati/tests/test_resources.py, iati/tests/test_version.py, iati/version.py
This allows `==` to be used to check whether a value is this or not, rather than requiring use of `is`. By doing this, it gives more scope to change the value in the future.
A constant has been added to contain this value, and should be used if this meaning is required.
For original explanation for change, see: https://github.com/IATI/pyIATI/issues/218#issuecomment-364086162
=> Change constant meaning 'version independent' to not None

CHANGELOG.md, iati/data.py, iati/resources/lib_data/validation_err_codes.yaml, iati/tests/test_data.py, iati/tests/test_utilities.py, iati/tests/test_validator.py, iati/tests/utilities.py, iati/utilities.py, iati/validator.py
#286 should be merged first
lxml does not support strings with an encoding declaration. They must be bytes objects if there is an encoding declaration. Previously, this error was grouped in with others. This separates two possible ValueErrors that lxml may raise so that it's clearer.
This issue was highlighted in #285
=>  Make visible an error message about unsupported values 

iati/tests/conftest.py, iati/tests/test_codelists.py, iati/tests/test_data.py, iati/tests/test_default.py, iati/tests/test_rulesets.py, iati/tests/test_schemas.py, iati/tests/test_utilities.py, iati/tests/test_validator.py, iati/tests/utilities.py, setup.cfg
As part of the version migration, it became necessary to explicitly specify versions rather than 'None' meaning 'latest version'. Locations where this happen had a TODO added. This led to things being a bit unclear.
Markers are now used to highlight where this happens.
=> Change TODOs about fixed versions to marks

CHANGELOG.md, iati/validator.py
`_check_codes` requests a particular version of the Version codelist. This allows it to obtain the latest version rather than the 2.02 version.
The implementation may need changing in the future depending on how discussions about the Version codelist progress.
=> Stop code in the validator module being fixed to 2.02

iati/version.py
Resolves linting errors in #273 - shown in (Travis build 2741](https://travis-ci.org/IATI/pyIATI/builds/355385616).
**pylint**
```
$ make pylint
pylint iati/
Using config file /home/travis/build/IATI/pyIATI/.pylintrc
************* Module iati.version
C: 53, 0: Trailing whitespace (trailing-whitespace)
```
**flake8**
```
$ make flake8
flake8 iati/
iati/version.py:53:1: W293 blank line contains whitespace
```
=> Fixes blank line contains whitespace linting error

.travis.yml, CHANGELOG.md, iati/resources.py, setup.py
Fixes #300
The reasons for removal are details in #300
At this very point, the code still works with Python 3.4. Testing against this version, however, is being stopped. This means that at some unknown point in the future pyIATI will stop working with Python 3.4.
=> Remove python 3.4 support

.travis.yml, CHANGELOG.md, iati/codelists.py, iati/data.py, iati/resources.py, iati/resources/lib_data/validation_err_codes.yaml, iati/rulesets.py, iati/schemas.py, iati/tests/fixtures/filepaths.py, iati/tests/resources.py, iati/tests/test_codelists.py, iati/tests/test_constants.py, iati/tests/test_data.py, iati/tests/test_default.py, iati/tests/test_resources.py, iati/tests/test_rulesets.py, iati/tests/test_schemas.py, iati/tests/test_test.py, iati/tests/test_utilities.py, iati/tests/test_validator.py, iati/tests/test_version.py, iati/tests/utilities.py, iati/utilities.py, iati/validator.py, requirements-dev.txt, setup.py
The reasons for removal are detailed in #301
The tests no longer pass when run with Python 2.7.
Further work could be undertaken to utilise a greater range of Python 3 features. This commit merely removes attempts to test at 2.7, as well as the shims to enable this.
=> Remove python 2.7 support
