setup.cfg
Restrict where tests are run from.
=> Add pytest ini

Makefile, README.md, docs/source/conf.py, iati/core/codelists.py, iati/core/data.py, iati/core/default.py, iati/core/resources.py, iati/core/schemas.py, iati/core/tests/test_codelists.py, iati/core/tests/test_constants.py, iati/core/tests/test_data.py, iati/core/tests/test_resources.py, iati/core/tests/test_schemas.py, iati/core/tests/test_test.py, iati/core/tests/test_utilities.py, iati/core/tests/utilities.py, iati/core/utilities.py, iati/test/test_validate.py, requirements-dev.txt, setup.cfg, setup.py
Reverts IATI/iati.core#32 because the `fix-linting` branch should have been merged to `dev`, not `master`.
=> Revert "Fix linting" (#32)

iati/core/data.py, iati/core/tests/test_codelists.py, iati/core/tests/test_data.py, iati/core/tests/test_default.py, iati/core/tests/test_schemas.py, iati/core/tests/test_utilities.py, iati/core/utilities.py
=> Switch tests to use `pytest.raises()`

iati/core/schemas.py, iati/core/tests/test_schemas.py
This adds a set in a similar way to how Codelists are managed
=> Add rulesets property to Schemas

iati/core/rulesets.py, iati/core/tests/test_rulesets.py
This tidies up the tests used to check that Rules have initialised correctly.
=> Improved Rule initialisation tests

iati/core/__init__.py, iati/core/default.py, iati/core/tests/test_default.py, iati/core/tests/test_rulesets.py
This makes specific Rule types consistent with other primary classes.
=> Provide shorthand import for specific Rules

iati/core/rulesets.py
This removes the other access to case attributes.
=> self.case['regex'] -> self.regex in Rules

iati/tests/test_validator.py, iati/validator.py
Check to see whether a Validation Error Log contains an error with the specified name.
=> Check validator err log contents

iati/validator.py
Fixes for review comments in #90 while bypassing a branching fail.
=> Fix a couple of docstrings

docs/source/iati.core.rst, docs/source/iati.core.tests.rst, docs/source/iati.rst, docs/source/iati.tests.rst, iati/core/__init__.py, iati/core/data.py, iati/core/default.py, iati/core/resources.py, iati/core/tests/test_codelists.py, iati/core/tests/test_data.py, iati/core/tests/test_resources.py, iati/core/tests/test_schemas.py, iati/core/tests/test_utilities.py, iati/core/tests/utilities.py, iati/core/utilities.py, iati/validate.py
This will allow it to be merged into `master`
=> Fix lintin errors in dev (bruv)

iati/core/tests/utilities.py, iati/tests/test_validator.py, iati/validator.py
A refactor of validation functionality.
=> Validation refactor

iati/core/rulesets.py, iati/core/tests/test_rulesets.py
This provides a string output along the lines of https://github.com/IATI/IATI-Rulesets/blob/version-2.02/iatirulesets/text.py
=> Customise rule string output

iati/core/tests/test_rulesets.py, iati/core/tests/utilities.py
=> Add check that data can be invalidated against the Standard Ruleset

iati/core/rulesets.py
Less and more were confused due to copypaste error
=> Fix a copypaste error

iati/core/default.py, iati/core/schemas.py, iati/core/tests/conftest.py, iati/core/tests/test_default.py, iati/core/tests/test_resources.py, iati/core/tests/test_schemas.py, iati/core/tests/test_utilities.py, iati/core/tests/utilities.py, iati/core/utilities.py, iati/tests/test_validate.py, iati/validate.py
This will allow `dev` to be merged into `master`.
=> Fix linting errors

iati/core/resources.py, iati/core/tests/test_resources.py, iati/core/tests/test_schemas.py
These changes were present in dev, so it makes sense to fix them in dev.
=> Fix changes requested in review for #154

docs/source/iati.core.rst, docs/source/iati.core.tests.rst, docs/source/iati.rst, docs/source/iati.tests.rst, iati/core/codelists.py, iati/core/constants.py, iati/core/data.py, iati/core/default.py, iati/core/resources.py, iati/core/rulesets.py, iati/core/schemas.py, iati/core/tests/test_codelists.py, iati/core/tests/test_resources.py, iati/core/tests/test_schemas.py, iati/core/utilities.py
There is a big chunk of changes heading towards `master`. This improves the documentation is a range of ways.
=> Various improvements to documentation

iati/core/default.py, iati/core/resources.py, iati/core/resources/lib_data/validation_err_codes.yaml, iati/core/resources/test_data/202/invalid_sum.xml, iati/core/resources/test_data/202/valid_sum.xml, iati/core/rulesets.py, iati/core/schemas.py, iati/core/tests/conftest.py, iati/core/tests/test_codelists.py, iati/core/tests/test_data.py, iati/core/tests/test_default.py, iati/core/tests/test_rulesets.py, iati/core/tests/utilities.py, iati/tests/conftest.py, iati/tests/test_validator.py, iati/validator.py
=> Various improvements to specific Rule validation

iati/core/resources/test_data/202/invalid_sum.xml, iati/core/resources/test_data/202/valid_sum.xml, iati/core/rulesets.py, iati/core/tests/test_rulesets.py
Add a test to sum non-numbers, so causing a `ValueError` to be raised.
=> Sum non numbers

LICENSES-3RD-PARTY.txt, docs/source/iati.core.tests.rst, iati/core/codelists.py, iati/core/constants.py, iati/core/data.py, iati/core/default.py, iati/core/resources.py, iati/core/resources/test_data/202/invalid_dateorder.xml, iati/core/resources/test_data/202/valid_dateorder.xml, iati/core/rulesets.py, iati/core/schemas.py, iati/core/tests/test_codelists.py, iati/core/tests/test_constants.py, iati/core/tests/test_data.py, iati/core/tests/test_resources.py, iati/core/tests/test_rulesets.py, iati/core/tests/test_schemas.py, iati/core/tests/test_utilities.py, iati/core/utilities.py, requirements-dev.txt
The PR indicates that there are merge conflicts for the merge to occur. This should fix the conflicts.
Going via 3rd branch to make it less likely that things break.
=> Fix conflicts for #145

CHANGELOG.md
The intention is to have something to call `0.1.0` today
=> Update version number and release date in changelog - 0.1.0

README.md
The name change appears to have now propogated
=> Update requires.io badges

README.md
=> Flatten the stability badges

CHANGELOG.md, iati/resources/standard/1-04/codelists/BudgetIdentifier.xml, iati/resources/standard/1-05/codelists/BudgetIdentifier.xml, iati/resources/standard/2-01/codelists/BudgetIdentifier.xml, iati/resources/standard/2-02/codelists/BudgetIdentifier.xml, iati/resources/standard/codelists_non_embedded/CRSChannelCode.xml, iati/resources/standard/codelists_non_embedded/CollaborationType.xml, iati/resources/standard/codelists_non_embedded/Country.xml, iati/resources/standard/codelists_non_embedded/IATIOrganisationIdentifier.xml, iati/resources/standard/codelists_non_embedded/Region.xml, iati/resources/standard/codelists_non_embedded/Sector.xml, iati/resources/standard/codelists_non_embedded/SectorCategory.xml
Brings in Codelist changes since 2017-08-07.
=> Update SSOT to latest content as of 2017-11-14

CHANGELOG.md, iati/codelists.py, iati/rulesets.py, iati/tests/conftest.py, iati/tests/test_rulesets.py
Provides the functionality to check Rule and Ruleset equality.
Part of #245
=> Test Rule and Ruleset equality

iati/schemas.py, iati/tests/conftest.py, iati/tests/test_codelists.py, iati/tests/test_schemas.py
Provides the functionality to check Schema equality.
**PRs to merge first (this builds upon them):**
=> Test schema equality

CHANGELOG.md, iati/default.py, iati/resources.py, iati/tests/test_resources.py
Add functions required by #258 to make `resources.py` consistent
Fixes #258 (the remainder that wasn't added via #259)
=> Add resources functions

iati/utilities.py
It was unclear whether a relative or absolute path is required. This clarifies the situation.
=> Improve documentation to clarify absolute rather than relative paths

CHANGELOG.md, iati/rulesets.py, requirements-dev.txt, setup.py
This is being done manually since requires.io is being a bit quiet
=> Update requirements 2018-01-25

.gitignore, .travis.yml, CHANGELOG.md, docs/source/index.rst, iati/tests/test_rulesets.py, iati/tests/test_version.py, iati/utilities.py
There were a number of errors and a missing file that mean the docs were not building. This makes the changes required for the docs to build.
There are still a couple of warnings, though at least the docs build.
=> Make the docs generate

README.md
The branch is very out of date.
=> Remove mention of edit-docs branch

README.md
~# ENSURE #310 IS MERGED FIRST~ <- Now done
=> Add validation to readme

README.md, iati/data.py, iati/version.py
Updates all issues arising with the README
Adds todo for Datasets in `data.py`
Updates README with correct info for generating the local docs site
Updates some issues arising with docstrings in pyIATI code.
=> Update docs gen, update README
